name: Zip

on:
  push: { branches: [main]}

jobs:
  build:
    name: zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1.0.0
        with:
          files: assets pack.mcmeta pack.png
          recursive: true
          dest: result.zip
      - uses: actions/upload-artifact@v2
        with:
          name: result.zip
          path: ${{ github.workspace }}/result.zip
